stages:
  - test
  - deploy

variables:
  REPO_NAME: gitlab.com/alenrig/converter
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_USERNAME: $CI_REGISTRY_USER
  DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD

format:
  image: golang:latest
  stage: test
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

release:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind

  variables:
    GIT_DEPTH: 0

  script: |
    docker run --rm --privileged \
      -v $PWD:/go/src/gitlab.com/alenrig/converter \
      -w /go/src/gitlab.com/alenrig/converter \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e DOCKER_USERNAME -e DOCKER_PASSWORD -e DOCKER_REGISTRY  \
      -e GITLAB_TOKEN \
      goreleaser/goreleaser release --rm-dist

  only:
    refs:
      - tags
